### ISSUE TITLE
Лишняя вложенность при генерации ?

### ISSUE THREAD

**Issue by kiokumicu** [SpectralDragon/viperSwift#1]
При генерации с помощью вашего шаблона получаю следующую вложенность
Project/Modules/FirstModule/Module/[папки с файлами]
Мне кажется должно быть
Project/Modules/FirstModule/[папки с файлами]

**Comment by SpectralDragon** [comment]
Это сделано для того, чтобы сделать папку Project/Modules/FirstModule/Storyboard и хранить там Storyboard для этого модуля.

**Comment by SpectralDragon** [comment]
Но при желании всегда можно это удалить :)
